In [1]:
import numpy as np

In [2]:
# Check numpy version
print(np.__version__)

2.1.2


In [49]:
# Definition : NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

# Creating a array using numpy

# dtype : int, float, complex, bool, object, etc, it is used to set the data type of elements in the array.
myArr = np.array([1, 2, 3, 4, 5], dtype=int)
# print(a)
# print(type(a))

# Two dimensional array
# b = np.array([[1, 2, 3], [4, 5, 6]])
# print(b)
# print(type(b))

# ndmin : This parameter is used to define the minimum number of dimensions of the created array.
# c = np.array([1, 2, 3, 4, 5], ndmin=2)
# print(c)
# print(type(c))

# dtype : complex, it is used to set the data type of elements in the array.
# d = np.array([1, 2, 3, 4, 5], dtype=complex)
# print(d)

# Create an array filled with zeros.
# a = np.zeros(5)

# Create an array filled with ones.
# a = np.ones(6)

# np.empty()
# a = np.empty(5)

# np.eye() : It is used to create a 2-D array with ones on the diagonal and zeros elsewhere.
a = np.eye(3)

# np.linspace() : It is used to create an array with evenly spaced values between the specified range.
a = np.linspace(1, 5, 10)

# np.arange() : It is used to create an array with evenly spaced values between the specified range.
a = np.arange(1, 6, 2)

# np.random.rand() : It is used to create an array with random values between 0 and 1.
a = np.random.rand(5)

# np.random.randn() : It is used to create an array with random values between 0 and 1.
a = np.random.randn(5)

# np.random.randint() : It is used to create an array with random integers between the specified range.
a = np.random.randint(1, 10, 5)


print(a)

[2 6 2 9 3]


In [40]:
# Array Attributes

a = myArr
print(a)

# shape : It is used to get the shape of an array.
# print(a.shape)

# ndim : It is used to get the number of dimensions of an array.
# print(a.ndim)

# nszie : It is used to get the number of elements in an array.
# print(a.size)

# dtype : It is used to get the data type of an array.
# print(a.dtype)

# itemsize : It is used to get the size of an element in an array.
# print(a.itemsize)


[1 2 3 4 5]
8


In [63]:
# Array Manipulation
a = np.random.randint(1, 10, 5)
print(f"Original Array : {a}")

# reshape() : It is used to change the shape of an array.
b = a.reshape(1, 5)
# print(b)

# transpose() : It is used to transpose an array.
b = a.transpose()
# print(b)

# ravel() : It is used to flatten an array.
b = a.ravel()
# print(b)

# concatenate() : It is used to concatenate two arrays.
b = np.random.randint(1, 10, (3, 3))
c = np.random.randint(1, 10, (3, 3))
d = np.concatenate((b, c))
# print(d)

# vstack() : It is used to stack arrays vertically.
d = np.vstack((b, c))
# print(d)

# hstack() : It is used to stack arrays horizontally.
d = np.hstack((b, c))
print(d)



Original Array : [7 1 9 7 9]
[[7 4 4 3 6 7]
 [9 5 6 1 2 5]
 [4 8 7 2 8 8]]


In [67]:
# Array indexing and slicing
a = np.random.randint(1, 10, 5)
print(f"Original Array : {a}")

# Indexing
# print(a[0])

# Slicing
# syntax : array[start:stop:step]
print(a[1:4])

Original Array : [5 2 3 9 2]
[2 3 9]


In [71]:
# Mathematical Operations
a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(f"Original Array a : {a}")
print(f"Original Array b : {b}")


# Addition
# b = a + 5
# print(f"Addition : {b}")

# # add two arrays
# b = a + b
# print(f"Addition : {b}")

# Subtraction
# b = a - 5

# Multiplication
# b = a * 5

# Division
# b = a / 5

# Exponentiation
# b = a ** 2

# Modulus
# b = a % 2

Original Array a : [7 9 6 7 1]
Original Array b : [5 9 5 8 2]
Addition : [12 18 11 15  3]


In [82]:
# Aggregation Functions
a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(f"Original Array a : {a}")
print(f"Original Array b : {b}")

# sum() : It is used to get the sum of all elements in an array.
print(a.sum())

# prod() : It is used to get the product of all elements in an array.
print(a.prod())

# mean() : It is used to get the mean of all elements in an array.
print(a.mean())

# median() : It is used to get the median of all elements in an array.
print(np.median(a))

# std() : It is used to get the standard deviation of all elements in an array.
print(a.std())

# var() : It is used to get the variance of all elements in an array.
print(a.var())

# min() : It is used to get the minimum value of all elements in an array.
print(a.min())

# max() : It is used to get the maximum value of all elements in an array.
print(a.max())


Original Array a : [3 6 9 6 2]
Original Array b : [1 7 1 1 3]
26
1944
5.2
6.0
2.4819347291981715
6.160000000000001
2
9
