<h1>Learning Numpy</h1>

In [2]:
# Importing
import numpy as np

In [3]:
# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Printing the array
print("1D Array:")
print(arr)

# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Printing the 2D array
print("\n2D Array:")
print(arr_2d)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Get dimensions of the array

# .ndim => returns the number of dimensions of the array

print("\nDimensions of the array:")
print("Dimensions of 1D array", + arr.ndim)
print("Dimensions of 2D array", + arr_2d.ndim)


Dimensions of the array:
Dimensions of 1D array 1
Dimensions of 2D array 2


In [15]:
# Shape of the array
print("\nShape of the array:")
print(arr.shape)
print(arr_2d.shape)

# Type of the array
print("\nType of the array:")
print(type(arr))
print(type(arr_2d))

# Get type using dtype
print("\nType of the array using dtype:")
print(arr.dtype)
print(arr_2d.dtype)


Shape of the array:
(5,)
(2, 3)

Type of the array:
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

Type of the array using dtype:
int64
int64


In [ ]:
# Creating an array with a specific datatype
arr_int = np.array([1, 2, 3, 4, 5], dtype='int32')
print("\nArray with specific datatype:")
print(arr_int)
print("Data type of the array:", arr_int.dtype)

# astype() method to convert the datatype of an existing array
# arr_float = arr_int.astype('float64')
arr_int_16 = arr_int.astype('int16')
print("\nArray converted to int16:")
print(arr_int_16)
print("Data type of the array:", arr_int_16.dtype)


Array with specific datatype:
[1 2 3 4 5]
Data type of the array: int32

Array converted to int16:
[1 2 3 4 5]
Data type of the array: int16


In [ ]:
# Itemsize of the array
# itemsize => returns the length of each element of the array in bytes
print("\nItemsize of the array:")
print(arr.itemsize)
print(arr)


Itemsize of the array:
4
[1 2 3 4 5]


In [24]:
# Get size
# size => returns the number of elements in the array
print("\nSize of the array:")
print(arr.size)


Size of the array:
5
