<h1>KNN - K Nearest Neighbors Algorithms</h1>

In [ ]:
# KNN - K Nearest Neighbors

# Step 1: Importing the libraries
import pandas as pd

# Step 2: Importing the dataset
dataset = pd.read_csv('../../../0.Databases/Fish-Market-dataset/Fish.csv')
X = dataset.iloc[:, 1:].values # Independent variables/Features
y = dataset.iloc[:, 0].values # Dependent variable/Target

# Step 3: Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Step 4: Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Step 5: Training the K-NN model on the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)

# Fit the model
classifier.fit(X_train, y_train)

# Compute accuracy
accuracy = classifier.score(X_test, y_test)
print(accuracy)

# Step 6: Predicting the Test set results
y_pred = classifier.predict(X_test)

# Step 7: Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

# Step 8: Visualising the Training set results
# from matplotlib.colors import ListedColormap

# X_set, y_set = X_train, y_train

# X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
#                      np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))

# plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
#              alpha = 0.75, cmap = ListedColormap(('red', 'green', 'blue')))
# plt.xlim(X1.min(), X1.max())
# plt.ylim(X2.min(), X2.max())
# for i, j in enumerate(np.unique(y_set)):
#     plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
#                 c = ListedColormap(('red', 'green', 'blue'))(i), label = j)
# plt.title('K-NN (Training set)')
# plt.xlabel('Length')
# plt.ylabel('Weight')
# plt.legend()
# plt.show()

# Step 9: Visualising the Test set results
# from matplotlib.colors import ListedColormap

# X_set, y_set = X_test, y_test

# X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
#                      np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
# plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
#              alpha = 0.75, cmap = ListedColormap(('red', 'green', 'blue')))
# plt.xlim(X1.min(), X1.max())
# plt.ylim(X2.min(), X2.max())
# for i, j in enumerate(np.unique(y_set)):
#     plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
#                 c = ListedColormap(('red', 'green', 'blue'))(i), label = j)
#     plt.title('K-NN (Test set)')
#     plt.xlabel('Length')
#     plt.ylabel('Weight')
#     plt.legend()
# plt.show()

# Step 10: Predicting a new result
# print(classifier.predict(sc.transform([[30, 6.7]])))

# Step 11: Predicting the probability of a new result
# print(classifier.predict_proba(sc.transform([[30, 6.7]])))

# Step 12: Using the elbow method to find the optimal number of neighbors
# error = []
# for i in range(1, 40):
#     knn = KNeighborsClassifier(n_neighbors=i)
#     knn.fit(X_train, y_train)
#     pred_i = knn.predict(X_test)
#     error.append(np.mean(pred_i != y_test))
#     print(np.mean(pred_i != y_test))

# plt.figure(figsize=(12, 6))
# plt.plot(range(1, 40), error, color='red', linestyle='dashed', marker='o', markerfacecolor='blue', markersize=10)
# plt.title('Error Rate K Value')
# plt.xlabel('K Value')
# plt.ylabel('Mean Error')
# plt.show()

# Step 13: Using the elbow method to find the optimal number of neighbors
# error_rate = []

[[6 0 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 8 0 1 0 0]
 [0 0 1 4 0 0 0]
 [0 0 4 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 3 0 0 0 0]]
0.625


In [ ]:
# Import required libraries
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

# Sample Data: Assume `X` is feature data and `y` is target labels
X = np.array([[2, 3], [1, 2], [3, 5], [6, 7], [7, 8], [8, 10]])  # Feature data
y = np.array([0, 0, 0, 1, 1, 1])  # Labels (0 or 1)

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# test_size: proportion of the dataset to include in the test split, default is 0.25
# random_state: controls the shuffling applied to the data before applying the split, default is None
# stratify: array-like or None (default=None), if not None, data is split in a stratified fashion, using this as the class labels, pass an array of the same length as the input data
# stratify=y: ensures that the training and test sets have approximately the same percentage of samples of each target class as the complete set

# Print training and test sets to diagnose issue
print("Training data:", X_train)
print("Training labels:", y_train)
print("Test data:", X_test)
print("Test labels:", y_test)

# Initialize the KNN classifier with K=3
knn = KNeighborsClassifier(n_neighbors=3)

# Train the model
knn.fit(X_train, y_train)

# Make predictions
y_pred = knn.predict(X_test)

# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

Training data: [[ 8 10]
 [ 3  5]
 [ 7  8]
 [ 6  7]]
Training labels: [1 0 1 1]
Test data: [[2 3]
 [1 2]]
Test labels: [0 0]
Model Accuracy: 0.00


In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()
X = iris.data  # Feature data
y = iris.target  # Labels (setosa, versicolor, virginica)

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Print training and test sets
print("Training data:", X_train[:5])  # Show first 5 rows
print("Training labels:", y_train[:5])  # Show first 5 labels
print("Test data:", X_test[:5])  # Show first 5 test samples
print("Test labels:", y_test[:5])  # Show first 5 test labels

# Initialize the KNN classifier with K=3
knn = KNeighborsClassifier(n_neighbors=3)

# Train the model
knn.fit(X_train, y_train)

# Make predictions
y_pred = knn.predict(X_test)

# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

Training data: [[5.5 2.4 3.7 1. ]
 [6.3 2.8 5.1 1.5]
 [6.4 3.1 5.5 1.8]
 [6.6 3.  4.4 1.4]
 [7.2 3.6 6.1 2.5]]
Training labels: [1 2 2 1 2]
Test data: [[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]]
Test labels: [1 0 2 1 1]
Model Accuracy: 1.00
