Resources to learn or taking help from these...
1. w3school : https://www.w3schools.com/python/python_arrays.asp

In [2]:
# import numeric python library, that is used for working with arrays & matrices
import numpy as np # type: ignore

# create array from list
my_array = np.array([1, 2, 3, 4, 5])

# print array
print(my_array)

[1 2 3 4 5]


In [11]:
# taking array input from user
arr = input().strip().split(' ')

# input() is used to take input from user, it will take input as string
# strip() is used to remove leading and trailing whitespaces
# split() is used to split the string into list of strings

# convert list of strings to list of integers
arr = list(map(int, arr))

# map() is used to apply a function to each element of the list
# list is used to convert map object to list

print(arr)

[1, 2, 3, 4, 5]


In [3]:
# Reverse a array

# First method using splice operator
print(my_array[::-1])

# Second method using swapping
def reverse_array(arr):
    for i in range(len(arr)//2):
        arr[i], arr[-i-1] = arr[-i-1], arr[i]
    return arr

data = reverse_array(my_array)
print(data)

[5 4 3 2 1]
[5 4 3 2 1]


In [6]:
# Sum of array elements
def sumOfArray(arr):
    return sum(arr)

print(sumOfArray(my_array))

15


In [8]:
# Finding Maximum Element
def maxEle(arr):
    return max(arr)

print(maxEle(my_array))

5


In [11]:
# Removing Duplicates
def removeDuplicates(arr):
    return list(set(arr))

# set() is used to remove duplicates from list
# list() is used to convert object to list/Array

print(removeDuplicates([1, 2, 3, 4, 5, 1, 2, 3, 4, 5]))

[1, 2, 3, 4, 5]


In [12]:
#Finding Average
def average(arr):
    return sum(arr) / len(arr)

print(average(my_array))

3.0


In [15]:
# Sorting Array in Ascending Order
def sortArray(arr):
    return sorted(arr)

# sorted() is used to sort the array in ascending order

print(sortArray([8, 5, 2, 7, 3, 1, 6, 4]))

# Sorting Array in Descending Order
def sortArrayDesc(arr):
    return sorted(arr, reverse=True)

print(sortArrayDesc([8, 5, 2, 7, 3, 1, 6, 4]))

# sorted() function returns a sorted list of the specified iterable object.
# Syntax: sorted(iterable, key, reverse)
# iterable: Required. The sequence to sort, list, dictionary, tuple etc.
# key: Optional. A Function to execute to decide the order. Default is None
# reverse: Optional. A Boolean. False will sort ascending, True will sort descending. Default is False

[1, 2, 3, 4, 5, 6, 7, 8]
[8, 7, 6, 5, 4, 3, 2, 1]


In [18]:
# Checking if Array is Palindrome
def isPalindrome(arr):
    for i in range(len(arr)):
        if arr[i] != arr[len(arr) - 1 - i]:
            return False
    return True

print(isPalindrome([1, 2, 3, 2, 1]))
print(isPalindrome([1, 1, 3, 2, 1]))

True
False


In [4]:
def arrays(arr):
    # Convert the input list to a NumPy array of type float and reverse it
    return np.array(arr, float)[::-1]

# Read the space-separated numbers as input and split them directly by whitespace
arr = input().strip().split(' ')
result = arrays(arr)
print(result)


[5. 3. 2. 1.]


In [3]:
first_array = np.array([1,2,3])
second_array = np.array([3,4,5])

def concatenate(first_array, second_array):
    return np.concatenate((first_array, second_array))

print(concatenate(first_array, second_array))

[1 2 3 3 4 5]


In [12]:
# Traversal of array
def traversal(arr):
    for i in arr:
        print(i, end=" ")

traversal([1, 2, 3, 4, 5])

# newline
print()

def reversedTraversal(arr):
    for i in arr[::-1]:
        print(i, end=" ")

reversedTraversal([1, 2, 3, 4, 5])

1 2 3 4 5 
5 4 3 2 1 

In [15]:
# Search in array
def search(arr, x):
    for i in range(len(arr)):
        if(arr[i] == x):
            return i
    return -1

print(search([1, 2, 3, 4, 5], 3))
print(search([1, 2, 3, 4, 5], 30))

2
-1


In [29]:
# Delete element in array using index
def deleteElement(arr, index):
    del arr[index]
    return arr

arr = [1, 2, 3]
index = 1
result = deleteElement(arr, index)
print(*result)

# del, removes the element at the specified index

# The * symbol is used to unpack the elements of a list (or any iterable) when passed as arguments to a function or during printing.
# In the context of printing a list, using * allows you to print the elements of the list separated by spaces, without printing the list brackets [ ].
# With *, 1 2 3
# Without *, [1, 2, 3]


# Delete element in array using value
def deleteElementValue(arr, value):
    arr.remove(value)
    return arr

arr = [1, 2, 3]
value = 2
result = deleteElementValue(arr, value)
print(*result)

# remove() removes the first occurrence of the specified value

# Remove all occurrences of element in array
def removeAllOccurrences(arr, value):
    return list(filter(lambda x: x != value, arr))

arr = [1, 2, 3, 2, 4, 2, 5]
value = 2
result = removeAllOccurrences(arr, value)
print(*result)

1 3
1 3
1 3 4 5


In [30]:
# Update element in array
def updateElement(arr, index, value):
    arr[index] = value
    return arr

arr = [1, 2, 3]
index = 1
value = 5
result = updateElement(arr, index, value)
print(*result)

1 5 3


Searching Techniques Algorithms

In [34]:
# Searching Algorithm

# Linear Search
# Definition: Linear search is a searching algorithm that finds the position of a target value within a list.
# It sequentially checks each element of the list for the target value until a match is found or until all the elements have been searched.
def linearSearch(arr, x):
    for i in range(len(arr)):
        if arr[i] == x:
            return i
    return -1

arr = [1, 2, 3, 4, 5]
x = 3
result = linearSearch(arr, x)
print(result)


# Binary Search (iterative)
# Definition: Binary search is a searching algorithm that finds the position of a target value within a sorted array.
# It compares the target value to the middle element of the array and eliminates half of the remaining elements based on the comparison.
def binarySearch(arr, x):
    low = 0
    high = len(arr) - 1
    while low <= high:
        mid = (low + high) // 2
        if arr[mid] < x:
            low = mid + 1
        elif arr[mid] > x:
            high = mid - 1
        else:
            return mid
    return -1

arr = [1, 2, 3, 4, 5]
x = 3
result = binarySearch(arr, x)
print(result)

# // is used for floor division, which means it rounds down to the nearest whole number
# result = 10 // 3
# print(result)  # Output: 3
# result = 11 // 3
# print(result)  # Output: 3


# Binary Search (recursive)
def binarySearchRecursive(arr, x, low, high):
    if low <= high:
        mid = (low + high) // 2
        if arr[mid] < x:
            return binarySearchRecursive(arr, x, mid + 1, high)
        elif arr[mid] > x:
            return binarySearchRecursive(arr, x, low, mid - 1)
        else:
            return mid
    return -1

arr = [1, 2, 3, 4, 5]
x = 3
result = binarySearchRecursive(arr, x, 0, len(arr) - 1)
print(result)

# Hashing sorting Algorithm
def hashSearch(arr, x):
    hashTable = {}
    for i in range(len(arr)):
        if arr[i] not in hashTable:
            hashTable[arr[i]] = i
    if x in hashTable:
        return hashTable[x]
    return -1

arr = [1, 2, 3, 4, 5]
x = 3
result = hashSearch(arr, x)
print(result)

2
2
2
2


Sorting Techniques Algorithms

In [1]:
# Sorting Techniques

# Bubble Sort
# Definition: Bubble sort is a simple sorting algorithm that repeatedly steps through the list, compares adjacent elements, and swaps them if they are in the wrong order.
# Time Complexity: O(n^2) in the worst case and O(n) in the best case

# Worst case
def bubbleSort(nums):
    for i in range(len(nums)-1, 0, -1):
        for j in range(i):
            if(nums[j] > nums[j+1]):
                temp = nums[j]
                nums[j] = nums[j+1]
                nums[j+1] = temp
    return nums

# Best case
def bubbleSort(nums):
    n = len(nums)
    for i in range(n-1):
        swapped = False  # Flag to track if any swap occurred
        for j in range(n-1-i):
            if nums[j] > nums[j+1]:  # Change here: Compare adjacent elements
                nums[j], nums[j+1] = nums[j+1], nums[j]  # Swap elements
                swapped = True  # Set flag to True if a swap occurred
        if not swapped:
            break  # If no swaps occurred, the array is already sorted
    return nums


# Test cases
test_cases = [
    [2, 5, 1, 6, 3],
    [10, 7, 8, 3, 2, 1, 5, 6, 4, 9],
    [1, 2, 3, 4, 5],
    [5, 4, 3, 2, 1],
    [1],
    [],
]

# Iterate over each test case
for i, nums in enumerate(test_cases):
    print(f"Test Case {i+1}:")
    print("Input:", nums)
    result = bubbleSort(nums.copy())  # Create a copy to avoid modifying the original list
    print("Sorted:", result)
    print()  # Empty line for better readability


Test Case 1:
Input: [2, 5, 1, 6, 3]
Sorted: [1, 2, 3, 5, 6]

Test Case 2:
Input: [10, 7, 8, 3, 2, 1, 5, 6, 4, 9]
Sorted: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Test Case 3:
Input: [1, 2, 3, 4, 5]
Sorted: [1, 2, 3, 4, 5]

Test Case 4:
Input: [5, 4, 3, 2, 1]
Sorted: [1, 2, 3, 4, 5]

Test Case 5:
Input: [1]
Sorted: [1]

Test Case 6:
Input: []
Sorted: []



In [2]:
# Quick Sort
# Definition: Quick sort is a sorting algorithm that uses a divide-and-conquer approach to sort an array.
# The idea is to pick an element as a pivot and partition the array around it.
# Time Complexity: O(n log n) average, O(n^2) worst case

# Worst case
def quickSortWorstCase(nums):
    if len(nums) <= 1:
        return nums
    pivot = nums[len(nums) // 2]
    left = [x for x in nums if x < pivot]
    middle = [x for x in nums if x == pivot]
    right = [x for x in nums if x > pivot]
    return quickSortWorstCase(left) + middle + quickSortWorstCase(right)

# Best case
def quickSortBestCase(nums):
    if len(nums) <= 1:
        return nums
    pivot = nums[len(nums) // 2]
    left, middle, right = [], [], []
    for x in nums:
        if x < pivot:
            left.append(x)
        elif x == pivot:
            middle.append(x)
        else:
            right.append(x)
    return quickSortBestCase(left) + middle + quickSortBestCase(right)

# Average case
def quickSortAverageCase(nums):
    if len(nums) <= 1:
        return nums
    pivot = nums[len(nums) // 2]
    left, middle, right = [], [], []
    for x in nums:
        if x < pivot:
            left.append(x)
        elif x == pivot:
            middle.append(x)
        else:
            right.append(x)
    return quickSortAverageCase(left) + middle + quickSortAverageCase(right)

# Test cases
nums = [5, 2, 4, 6, 1, 3]
print("Input:", nums)
print("Output:", quickSortWorstCase(nums))
print("Output:", quickSortBestCase(nums))
print("Output:", quickSortAverageCase(nums))

Input: [5, 2, 4, 6, 1, 3]
Output: [1, 2, 3, 4, 5, 6]
Output: [1, 2, 3, 4, 5, 6]
Output: [1, 2, 3, 4, 5, 6]
